version: '2'
services:

  ranking-worker:
    build: Apps/Ranking/Workers/Simple
    environment:
      - NEO4J_HOST=neo4j-readreplica.databases
      - NEO4J_AUTH=myneologin/myneopassword # TODO: (MG6) HIDE
      - POSTGRES_HOST=postgres.databases
    ports:
      - 8000:8000
