version: '2'
services:

  ranking-worker-simple:
    image: "userfeeds/apps-ranking-runners-simple:${CI_BRANCH}"
    environment:
      - RDB_GRAPH=graph_database
      - NEO4J_AUTH=myneologin/myneopassword # TODO: (MG6) HIDE
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: processing=true # TODO: (MG6) NOT PROCESSING
    dns_search: # https://github.com/rancher/rancher/issues/7026
      - rancher.internal
    external_links:
      - databases/neo4j-readreplica:graph_database # TODO: (MG6) FIXME
    links:
      - ranking-worker-queue:queue

  ranking-worker-queue:
    image: "userfeeds/apps-ranking-queue:${CI_BRANCH}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: processing=true # TODO: (MG6) NOT PROCESSING

  ranking-server:
    image: "userfeeds/apps-ranking-server:${CI_BRANCH}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: processing=true # TODO: (MG6) NOT PROCESSING
    links:
      - ranking-worker-queue:queue
